id = "jellyfin"
name = "Jellyfin Desktop"
description = "Jellyfin desktop client built with Qt WebEngine and libmpv. Supports audio passthrough, hardware decoding, and playback of more formats without transcoding."
params = ["version"]

[[steps]]
id = "clone"
cache = ["source"]
once = true
run = { args = [
    "git",
    "clone",
    "--depth",
    "1",
    "--single-branch",
    "--branch",
    "$(package.version?:master)",
    "--recurse-submodules",
    "--shallow-submodules",
    "https://github.com/jellyfin/jellyfin-desktop.git",
    "source",
] }

[[default.steps]]
id = "configure"
cache = ["build"]
run = "cmake -S source -B build -G Ninja -DCMAKE_BUILD_TYPE=MinSizeRel -DUSE_STATIC_MPVQT=ON"

[[default.steps]]
id = "build"
cache = ["build"]
run = "cmake --build build --parallel"

[[default.steps]]
id = "install"
run = [
    "sudo install -Dm755 build/src/jellyfin-desktop /usr/local/bin/jellyfin-desktop",
    "sudo install -Dm644 source/resources/meta/org.jellyfin.JellyfinDesktop.desktop /usr/local/share/applications/org.jellyfin.JellyfinDesktop.desktop",
    "sudo install -Dm644 source/resources/meta/org.jellyfin.JellyfinDesktop.appdata.xml /usr/local/share/metainfo/org.jellyfin.JellyfinDesktop.metainfo.xml",
    "sudo install -Dm644 source/resources/images/icon.svg /usr/local/share/icons/hicolor/scalable/apps/org.jellyfin.JellyfinDesktop.svg",
    "sudo update-desktop-database",
]

[[default.steps]]
id = "remove"
remove = true
run = [
    "sudo rm /usr/local/bin/jellyfin-desktop",
    "sudo rm /usr/local/share/applications/org.jellyfin.JellyfinDesktop.desktop",
    "sudo rm /usr/local/share/metainfo/org.jellyfin.JellyfinDesktop.metainfo.xml",
    "sudo rm /usr/local/share/icons/hicolor/scalable/apps/org.jellyfin.JellyfinDesktop.svg",
    "sudo update-desktop-database",
]
